### ISSUE TITLE
[BLU-2828] Modify `generatePath` to not be dependant on USDC

### ISSUE THREAD

**Issue by mauricedesaxe** [ToucanProtocol/OffsetHelper#11]
# Why

Right now the path generation ([code responsible for path generation](https://discord.com/channels/706114892666765375/1006598167707537561/1047149881883627581)) for the `OffsetHelper` either works as `USDC→poolToken` or as `inputToken→USDC→poolToken`.

Devs/users have tried creating `WETH→poolToken` pools and using them with the `OffsetHelper`, but because of the very inflexible routing the `OffsetHelper` uses this errors out ([example here](https://discord.com/channels/706114892666765375/1006598167707537561/1046878303836971048)).

There is a related internal issue [in Linear here](https://linear.app/toucan/issue/PROD-2828/modify-generatepath-to-not-be-dependant-on-usdc).

# Requirements

We want to modify the `generatePath` (maybe other code, I am not sure yet) such that the `OffsetHelper` would work with more paths in a dynamic way.

**Comment by SimasG** [comment]
Happy to take this on @lazaralex98.

Do we want to add support only for direct swaps with pre-defined pairs (i.e. WMATIC/MATIC/WETH - BCT/NCT) or do we also want to add additional functionality, like supporting direct (e.g. KLIMA - BCT, etc.) & multi-step (e.g. KLIMA - USDC - NCT, etc.) swaps with ad hoc pairs? I guess that would then move the responsibility to ensure liquidity for these new pools on the developers who want to use these new pairs.

**Comment by lazaralex98** [comment]
I think we want to move away from pre-defined pairs if we can. 

> like supporting direct (e.g. KLIMA - BCT, etc.) & multi-step (e.g. KLIMA - USDC - NCT, etc.) swaps with ad hoc pairs

We definitely want to support more freedom like that. This issued stemmed from somebody wanting to swap WETH-NCT direct.

> I guess that would then move the responsibility to ensure liquidity for these new pools on the developers who want to use these new pairs.

That actually could make a lot of sense. We could offer a few predefined paths and for anything extra of that, let the dev have more control over the path.

I'm not sure how this would look like in code and I know this is very poorly specified. So, please, bother me with any ideas or Qs you have.

**Comment by SimasG** [comment]
Ok, I think I have a working prototype. It is really ugly though.

The basic idea is as follows: add 3 optional arguments in the `generatePath` function:
1. `bool customPath` - true if a dev wants to create a custom path.
2. `bool multiStepPath` - true if a dev wants to create a multi-step (e.g. KLIMA - USDC - NCT, etc.) path.
3. `address _intermediaryToken` - provided if multiStepPath is true.

The problem is that optional arguments aren't supported in solidity at the moment. The current workaround is using [function overloading](https://docs.soliditylang.org/en/v0.8.13/contracts.html#function-overloading) - i.e. creating multiple functions with the same name but different input arguments & different logic.

I'm wondering how to test non-existing liquidity pairs but it seems to work. The biggest drawback is that we'd have to have 3 versions of **each** function (& its parents) where `generatePath` is executed - 1 version for the current (default) mode & 2 custom versions (one for custom direct swaps (i.e. `customPath`) and another for custom multi-step swaps (i.e. `bool multiStepPath` & `address _intermediaryToken`)). I haven't implemented everything yet but it would easily add hundreds of additional lines of code - something I'd like to avoid.

@lazaralex98 would love to hear your thoughts on this. Do any obvious improvements of this type of fix come to mind? Otherwise, I'm happy to create a draft PR for more clarity.

**Comment by lazaralex98** [comment]
I'm really sorry for the late answer man. You're right that this would add too many versions of each function. 

I wonder if we could extract the base functions of the `OffsetHelper` into a `BaseOffsetHelper` contract. Then have other contracts that implement it: one that uses a direct path, one that uses a multi-step path.

Or maybe we could have a `SwapPathGenerator` contract. The `OffsetHelper` would take the `path` as a param from the caller. And the caller would generate their path with `SwapPathGenerator`.

Honestly, I'd rather go for the second non-inheritance option just based on my feelings for inheritance.

These are just some very quick thoughts though. I'm not sure if they make sense in practice or what the tradeoffs are right now.

**Comment by SimasG** [comment]
My time to apologize for the late response :)

Could you clarify the second option a bit more? I'm having trouble understanding it.

**Comment by SimasG** [comment]
Came up with another, slightly more elegant solution.

Instead of nasty function overloading, we could add an additional argument for `generatePath` - an array of addresses called `customPath`. If the array is empty, everything runs business as usual. If it's not empty, it will be used as `path`. Here is the [implementation of the new function](https://github.com/SimasG/offset-helper-backend/blob/flexible-path-2/contracts/OffsetHelper.sol#L612).

Positives:

- Clear & short (~60 additional lines of code)

Negatives:

- Adds additional `customPath` argument for every function that is built on `generatePath` (15, to be exact)
- Doesn't work under the current way we set `eligibleTokenAddresses`.
  Currently, we set `eligibleTokenAddresses` on contract deployment & do not allow swaps with tokens that aren't in this mapping. To be honest, I don't understand why we should specify swappable token addresses within `eligibleTokenAddresses`. If a dev wants to use a custom path but there's no/not enough liquidity in those pools, the transaction should just fail (might be wrong). Although adding BCT & NCT as "eligible" does seem to make sense because they're the only redeemables we support atm.

  Would love to add tests for these custom paths but I'm having trouble simulating non-existent liquidity pools. Would appreciate any help here!

**Comment by GigaHierz** [comment]
Hi @SimasG , 

great work! I am taking over the communication here from Alex. I am currently working on updating the OffsetHelper, so, really grateful for all of your contributions!

For testing, I would suggest using the [hardhat fork](https://hardhat.org/hardhat-network/docs/guides/forking-other-networks) method, as the pools on the testnet are just not that liquid, and easy to create.
