### ISSUE TITLE
Replace using `balances` with `IERC20.balanceOf`

### ISSUE THREAD

**Issue by mauricedesaxe** [ToucanProtocol/OffsetHelper#14]
Accounting for token balances inside `OffsetHelper` is duplication and invites potential issues with them not matching each other. 

It'd be a good practice to try and replace all occurrences and usage of `balances` as a getter with `IERC20.balanceOf` instead. This should allow us to completely remove the `balances` mapping. This also entails:

- removing any place where we modified `balances` as now this state will be stored in the `IERC20` contracts
- cleaning up tests so they do not check for `OffsetHelper.balances` anymore but only for the `IERC20.balanceOf`
- **last:** adding a `balances` view function in `OffsetHelper` that uses `IERC20.balanceOf` (this is done for backward compatibility)

**Comment by SimasG** [comment]
How do we keep track of how much BCT/NCT belongs to which address since we actually allow to just deposit pool tokens via `deposit()` without immediately offsetting them?
    
 To solve this, we could remove any possibility for users to deposit/withdraw any tokens to the contract (aka remove `deposit()` & `withdraw()` functions) without offsetting right away. Ideally, the contract should either offset the given amount or fail to do so. It also gets rid of a ton of tests.
    
I prototyped a quick & dirty solution but I’m not sure what would happen if multiple users would call offset functions at the same time though.
